# Generated by Django 4.1.7 on 2024-11-10 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='checked',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rating_set',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='slug',
        ),
        migrations.AddField(
            model_name='rating',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='users.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='catalog.product'),
        ),
    ]
