# Generated by Django 4.1.7 on 2024-11-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('catalog', '0003_remove_comments_checked_remove_rating_rating_set_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.AddField(
            model_name='tag',
            name='title',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
